### ISSUE TITLE
numpy.core Memory allocation issues

### ISSUE THREAD

**Issue by ACastanza** [k3yavi/vpolo#3]
Hello, I'm running vpolo as part of a script in a debian based docker container (running on AWS via GenePattern) which has been allocated 64GB of RAM. When importing the quants I'm getting the following error:

```
Traceback (most recent call last):


  File "/opt/gpbeta_2/gp_home/taskLib/Convert.alevin.1.1814/alevin.vpolo.py", line 162, in <module>
    main()
  File "/opt/gpbeta_2/gp_home/taskLib/Convert.alevin.1.1814/alevin.vpolo.py", line 94, in main
    adata_working=vparser.read_quants_bin(quants)
  File "/opt/conda/lib/python3.8/site-packages/vpolo/alevin/parser.py", line 77, in read_quants_bin
    umi_matrix = csr_matrix((mat[2], mat[1], mat[0]), shape=(num_cbs, num_genes)).todense()
  File "/opt/conda/lib/python3.8/site-packages/scipy/sparse/base.py", line 847, in todense
    return asmatrix(self.toarray(order=order, out=out))
  File "/opt/conda/lib/python3.8/site-packages/scipy/sparse/compressed.py", line 1029, in toarray
    out = self._process_toarray_args(order, out)
  File "/opt/conda/lib/python3.8/site-packages/scipy/sparse/base.py", line 1185, in _process_toarray_args
    return np.zeros(self.shape, dtype=self.dtype, order=order)
numpy.core._exceptions.MemoryError: Unable to allocate 7.68 GiB for an array with shape (12023, 85684) and data type float64

```

The same Alevin quant file imports just fine using a MacOS system which has 16GB of RAM and combined with swap space, uses significantly less than the 64GB allocated in the docker image. I'm pretty sure this is a memory over-committing issue, but I would expect that this file should be able to be parsed on both systems.

The script can be found here: https://github.com/ACastanza/Convert.alevin/blob/main/src/alevin.vpolo.py
The corresponding docker container here: https://hub.docker.com/r/acastanza/convert_alevin
The data file generating the error is here: https://drive.google.com/file/d/1oOReRV3Z5P3MZKDI08gCBkilNX9k-6dT/view?usp=sharing
(To run the script, the tar.gz quants file is supplied as a path (or a newline delimited list of paths) in a .txt file)

**Comment by k3yavi** [comment]
Thanks @ACastanza , Seemingly I am calling `to_dense()` which is creating the issue. I think since the function was returning a dataframe and I think we can't create a sparse dataframe which initiated the `to_dense()` call. If you wan't you can always manually edit [this](https://github.com/k3yavi/vpolo/blob/master/vpolo/alevin/parser.py#L77) line to remove the `to_dense()` call and receive a sparse matrix if it helps. Happy to merge a PR if you get a chance.

**Comment by ACastanza** [comment]
The script I've written is designed to facilitate the conversion between the alevin output format and the anndata structure used for scvelo (per the alevin velocity tutorial). Would you have any reason to suspect that removing the to_dense() function would cause any particular issues with splitting apart the spliced and unspliced matrices on the basis of the gene ids, and then reassembling them into layers in an anndata file?

**Comment by k3yavi** [comment]
Oh I am sorry I missed the links to the scripts the first time, probably I missed the update to the issues. Yea so I don't expect any difference if you have or not have the `to_dense()` function call. I am not very familiar with the anndata format but I presume it can consume the sparse matrices directly. The variable `umi_matrix` [here](https://github.com/k3yavi/vpolo/blob/master/vpolo/alevin/parser.py#L77) is actually a sparse matrix if you don't call `to_dense()` function.  Once filled all it does is creates a dataframe and assign names to rows and cols [here](https://github.com/k3yavi/vpolo/blob/master/vpolo/alevin/parser.py#L129-L135), hope it helps !

**Comment by ACastanza** [comment]
After removing the to_dense() call I'm getting the following error:

```
Using rust mode with 12023 rows and 85684 columns
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/lib/python3.8/site-packages/vpolo/alevin/parser.py", line 130, in read_quants_bin
    alv.columns = gene_names
  File "/usr/local/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 5478, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "/usr/local/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py", line 670, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 220, in set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 1 elements, new values have 85684 elements
```

**Comment by k3yavi** [comment]
Oh so I wan't clear, so you have to return the `umi_matrix` which is a sparse matrix and the row and column names separately because unlike R, I don't think sparse matrix object can store row and column names, that's why the error.

**Comment by ACastanza** [comment]
Ok, so I was able to get vpolo to return a list containing the umi_matrix, the cell barcodes, and the gene IDs, but this definitely breaks my solution for splitting the spliced and unspliced matrices which relies on column intersection.

Edit: deleted the reply, the process was actually failing at a completely different point with the increased allocation

**Comment by ACastanza** [comment]
Weird thing, I doubled the allocation of RAM for the container from 32 to 64 GB and the error message changed from: `numpy.core._exceptions.MemoryError: Unable to allocate 7.68 GiB for an array with shape (12023, 85684) and data type float64`
to:
`numpy.core._exceptions.MemoryError: Unable to allocate 4.73 GiB for an array with shape (52856, 12023) and data type float64`

Why would doubling the amount of available memory only result in being able to allocate an additional 3GiB of the array?

**Comment by k3yavi** [comment]
I think the weirder part is why would the shape of the matrix change ? can you check the number of lines in the `quants_mat_rows.txt` and `quants_mat_cols.txt` files ?

**Comment by ACastanza** [comment]
That was my mistake, it had actually made it on to the second step where it splits the array and ran out of memory allocating the unspliced array after doubling the container memory.

**Comment by k3yavi** [comment]
Ok no worries, but does things work now ? I am a bit confused about what's still is the problem ?

**Comment by ACastanza** [comment]
I'm not sure.
The issue is that in order to split the spliced from unspliced genes, you have to slice the matrix that vpolo creates. The spliced and unspliced gene annotations that are needed to do this have to be retreived from a separate file, then each list has to be matched to the gene ids in the full matrix to create the separate spliced matrix and an unspliced matrices. When the full matrix was dense with column information it was simple to do this with column intersection. With a sparse matrix with detached column ids, slicing it is proving more difficult than I expected. I thought I'd had a solution but it was just shifting the memory allocation problem down the line.

**Comment by ACastanza** [comment]
I'm going to close this issue, it appears that there was a problem on our end where the spec of the machines we were requesting from AWS wasn't being honored. Now that this is resolved we're able to request enough memory to work with the large dense matrices. Thanks for your help!
