### ISSUE TITLE
Trouble opening the quants_tier_mat.gz output file from alevin in python

### ISSUE THREAD

**Issue by benstear** [k3yavi/vpolo#4]
Hi,

I am trying to open the file 'quants_tier_mat.gz'  from Alevin in Python but I keep getting unicode error messages.

I first unzip the file and then try to read it in but I keep getting UnicodeDecodeErrors.

What is the recommended way to open the quants_tier_mat.gz file?

Thank you,

Ben

**Comment by k3yavi** [comment]
Hi, the quants file is in th binary format. The functions provided in the python package should be able to directly import the compressed binary file and give you a dataframe. Consider changing mtype to tier and the function should import the tier matrix: https://github.com/k3yavi/vpolo/blob/master/vpolo/alevin/parser.py#L38

**Comment by benstear** [comment]
Ok thank you!
