### ISSUE TITLE
Can't load quants_tier_mat

### ISSUE THREAD

**Issue by ktpolanski** [k3yavi/vpolo#7]
I installed vpolo following [official instructions](https://combine-lab.github.io/alevin-tutorial/2018/output-format/):
```bash
conda install -c bioconda vpolo
```
I then attempted to load a `quants_tier_mat.gz`:
```python3
from vpolo.alevin import parser
alevin_df_tiers = parser.read_quants_bin("/home/jovyan/sharedData/jc48/23-07-19-alevin/BHF_F_Hea10402917/alevin", mtype="tier")
```
This explodes:
```
/home/jovyan/sharedData/jc48/23-07-19-alevin/BHF_F_Hea10402917/alevin/alevin
Using rust mode with 2200 rows and 184511 columns
thread '<unnamed>' panicked at 'can't read the EDS file: Custom { kind: UnexpectedEof, error: "failed to fill whole buffer" }', src/lib.rs:30:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jovyan/my-conda-envs/d2c/lib/python3.8/site-packages/vpolo/alevin/parser.py", line 76, in read_quants_bin
    mat = sce.read_quants(quant_file, num_cbs, num_genes)
SystemError: Rust panic
```
Of note, everything runs fine when I remove `mtype="tier"` from the call. It's the tier one that's putting up a fight, which is a bummer as it's the tier one I'm after - the non-tier one can be exported as MTX easily.

Some assistance please?

**Comment by k3yavi** [comment]
can you try `rmode="python"`, if it helps?

**Comment by ktpolanski** [comment]
That seems to have done the trick! The run time and resource footprint are both larger, but at least it works. Thank you very much!
